module.exports = {
  apps: [
    {
      name: "tls-auto-renewal-proxy",
      script: "./init.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      node_args: "--max-old-space-size=500",
      env: {
        NODE_ENV: "production",
        CHALLENGE_DIR: "/usr/src/app/.well-known/pki-validation",
        CERTIFICATE_DIR:'/usr/src/app/certificates',
        DB_CERT_DIR:'/usr/src/app/certs',
        DB_CA_DIR:'/usr/src/app/CAs',
        PORT: 3002,
        HTTPS_PORT: 443,
        HTTP_PORT: 80,
        SERVER_DRAIN_TIME: 60000,
        DOMAIN: "34.31.32.113",
        SMTP_PASS:'6j5c77375r4w9u9k'
      },
      error_file: "logs/err.log",
      out_file: "logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_size: "10M",
      rotate_logs: true,
    },
    {
      name: "tls-renewal",
      script: "./init_ssl-renewal.js",
      instances: 1,
      autorestart: false,
      watch: false,
      cron: "0 1 * * *",
      exec_mode: "fork",
      kill_timeout: 60000,
      wait_ready: true,
      listen_timeout: 60000,
      min_uptime: 10000,
      max_restarts: 3,
      restart_delay: 5000,
      stop_exit_codes: [0],
      env: {
        NODE_ENV: "production",
        RENEWAL_CHECK_INTERVAL: "86400000", // 24 hours in milliseconds
        CERTIFICATE_DIR:'/usr/src/app/certificates',
        DB_CERT_DIR:'/usr/src/app/certs',
        PORT: 3002,
        HTTPS_PORT: 443,
        DOMAIN: "34.31.32.113",
        DB_CA_DIR:'/usr/src/app/CAs',
        MAINTENANCE:false,
        RENEWAL:true,
        SMTP_PASS:'6j5c77375r4w9u9k'
      },
      error_file: "logs/ssl-err.log",
      out_file: "logs/ssl-out.log",
      max_size: "10M",
      rotate_logs: true,
      max_memory_restart: "1G",
    },
    {
      name: "server-maintenance",
      script: "./init_maintenance.js",
      instances: 1,
      autorestart: false,
      cron: "0 2 * * *",
      watch: false,
      exec_mode: "fork",
      kill_timeout: 60000,
      wait_ready: true,
      listen_timeout: 60000,
      min_uptime: 10000,
      max_restarts: 3,
      restart_delay: 5000,
      stop_exit_codes: [0],
      env: {
        NODE_ENV: "production",
        MAINTENANCE_INTERVAL: "86400000", // 24 hours in milliseconds
        CERTIFICATE_DIR:'/usr/src/app/certificates',
        DB_CERT_DIR:'/usr/src/app/certs',
        DB_CA_DIR:'/usr/src/app/CAs',
        PORT: 3002,
        HTTPS_PORT: 443,
        DOMAIN: "34.31.32.113",
        MAINTENANCE:true,
        RENEWAL:false,
        SMTP_PASS:'6j5c77375r4w9u9k'
      },
      error_file: "logs/maintenance-err.log",
      out_file: "logs/maintenance-out.log",
      max_size: "10M",
      rotate_logs: true,
      max_memory_restart: "1G",
    },
  ]
}